version: '3.7'
services:
  go-standard-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    # Map Some Attachment store directories
    volumes:
      - ./folder1:/app/folder1
    restart: always
    # Map Port from container to host
    ports:
      - 4000:3000
    depends_on:
      - postgres
    networks:
      - go-standard-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: standard_fiber_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-standard-network

volumes:
  postgres_data:

networks:
   go-standard-network:
    driver: bridge
